apiVersion: apps/v1
kind: Deployment
metadata:
  name: quickstart
  labels:
    app: quickstart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quickstart
  template:
    metadata:
      labels:
        app: quickstart
    spec:
      containers:
        - name: quickstart-app
          image: unfor19/docker-cats
          env:
            - name: APP_NAME
              value: baby
            - name: SIGTERM_STOP_TIMEOUT_SECONDS
              value: "10"
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: quickstart
spec:
  ports:
    - name: http
      targetPort: 8080
      port: 80
  selector:
    app: quickstart
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quickstart
spec:
  ingressClassName: nginx
  rules:
    - host: quickstart.kubemaster.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quickstart
                port:
                  number: 80
